import Foundation

struct EmojiEntry: Hashable {
    let char: String
    let keywords: String
}

struct EmojiCategory: Identifiable, Hashable {
    var id: String { name }
    let name: String
    let emojis: [EmojiEntry]
}

enum EmojiCatalog {
    static let categories: [EmojiCategory] = [
        EmojiCategory(name: "Smileys & People", emojis: [
            .init(char: "😀", keywords: "grinning happy face smile"),
            .init(char: "😃", keywords: "smiley happy"),
            .init(char: "😄", keywords: "smile happy joy"),
            .init(char: "😁", keywords: "beaming grin"),
            .init(char: "😆", keywords: "laugh laughing"),
            .init(char: "😅", keywords: "sweat laugh nervous"),
            .init(char: "🤣", keywords: "rofl laugh rolling"),
            .init(char: "😂", keywords: "joy crying tears laugh"),
            .init(char: "🙂", keywords: "slightly smile"),
            .init(char: "🙃", keywords: "upside down"),
            .init(char: "😉", keywords: "wink flirt"),
            .init(char: "😊", keywords: "blush smile"),
            .init(char: "😇", keywords: "halo angel innocent"),
            .init(char: "🥰", keywords: "love hearts"),
            .init(char: "😍", keywords: "heart eyes love"),
            .init(char: "🤩", keywords: "star struck excited"),
            .init(char: "😘", keywords: "kiss"),
            .init(char: "😗", keywords: "kissing"),
            .init(char: "😚", keywords: "kissing closed"),
            .init(char: "😙", keywords: "kissing smile"),
            .init(char: "🥲", keywords: "tear smile"),
            .init(char: "😋", keywords: "yum tongue tasty"),
            .init(char: "😛", keywords: "tongue"),
            .init(char: "😜", keywords: "wink tongue"),
            .init(char: "🤪", keywords: "zany crazy"),
            .init(char: "😝", keywords: "tongue squint"),
            .init(char: "🤑", keywords: "money mouth"),
            .init(char: "🤗", keywords: "hug hugging"),
            .init(char: "🤭", keywords: "hand over mouth"),
            .init(char: "🤫", keywords: "shush quiet"),
            .init(char: "🤔", keywords: "thinking think"),
            .init(char: "🤐", keywords: "zipper mouth"),
            .init(char: "😐", keywords: "neutral"),
            .init(char: "😑", keywords: "expressionless"),
            .init(char: "😶", keywords: "no mouth blank"),
            .init(char: "😏", keywords: "smirk"),
            .init(char: "😒", keywords: "unamused"),
            .init(char: "🙄", keywords: "eye roll"),
            .init(char: "😬", keywords: "grimace"),
            .init(char: "😌", keywords: "relieved"),
            .init(char: "😔", keywords: "pensive sad"),
            .init(char: "😪", keywords: "sleepy"),
            .init(char: "🤤", keywords: "drool"),
            .init(char: "😴", keywords: "sleep zzz"),
            .init(char: "😷", keywords: "mask sick"),
            .init(char: "🤒", keywords: "thermometer sick"),
            .init(char: "🤕", keywords: "head bandage hurt"),
            .init(char: "🤧", keywords: "sneeze"),
            .init(char: "🥵", keywords: "hot heat"),
            .init(char: "🥶", keywords: "cold freeze"),
            .init(char: "😎", keywords: "cool sunglasses"),
            .init(char: "🤓", keywords: "nerd glasses"),
            .init(char: "🧐", keywords: "monocle"),
            .init(char: "😕", keywords: "confused"),
            .init(char: "😟", keywords: "worried"),
            .init(char: "🙁", keywords: "frown"),
            .init(char: "😮", keywords: "open mouth"),
            .init(char: "😯", keywords: "hushed"),
            .init(char: "😲", keywords: "astonished"),
            .init(char: "😳", keywords: "flushed"),
            .init(char: "🥺", keywords: "pleading"),
            .init(char: "😦", keywords: "frowning open"),
            .init(char: "😢", keywords: "cry sad tear"),
            .init(char: "😭", keywords: "loudly crying sob"),
            .init(char: "😱", keywords: "scream fear"),
            .init(char: "😨", keywords: "fearful"),
            .init(char: "😰", keywords: "anxious sweat"),
            .init(char: "😥", keywords: "sad relieved"),
            .init(char: "😓", keywords: "downcast"),
            .init(char: "🤗", keywords: "hugging"),
            .init(char: "🤔", keywords: "thinking"),
            .init(char: "🥳", keywords: "party celebration"),
            .init(char: "🤠", keywords: "cowboy"),
            .init(char: "👻", keywords: "ghost"),
            .init(char: "💀", keywords: "skull death"),
            .init(char: "👽", keywords: "alien"),
            .init(char: "🤖", keywords: "robot bot"),
            .init(char: "👍", keywords: "thumbs up like"),
            .init(char: "👎", keywords: "thumbs down dislike"),
            .init(char: "👌", keywords: "ok"),
            .init(char: "✌️", keywords: "peace victory"),
            .init(char: "🤞", keywords: "fingers crossed luck"),
            .init(char: "🤟", keywords: "love you"),
            .init(char: "🤘", keywords: "rock horns"),
            .init(char: "👏", keywords: "clap applause"),
            .init(char: "🙌", keywords: "raised hands celebration"),
            .init(char: "🙏", keywords: "pray thanks please"),
            .init(char: "💪", keywords: "muscle strong"),
        ]),
        EmojiCategory(name: "Animals & Nature", emojis: [
            .init(char: "🐶", keywords: "dog puppy"),
            .init(char: "🐱", keywords: "cat kitten"),
            .init(char: "🐭", keywords: "mouse"),
            .init(char: "🐹", keywords: "hamster"),
            .init(char: "🐰", keywords: "rabbit bunny"),
            .init(char: "🦊", keywords: "fox"),
            .init(char: "🐻", keywords: "bear"),
            .init(char: "🐼", keywords: "panda"),
            .init(char: "🐨", keywords: "koala"),
            .init(char: "🐯", keywords: "tiger"),
            .init(char: "🦁", keywords: "lion"),
            .init(char: "🐮", keywords: "cow"),
            .init(char: "🐷", keywords: "pig"),
            .init(char: "🐸", keywords: "frog"),
            .init(char: "🐵", keywords: "monkey"),
            .init(char: "🙈", keywords: "see no evil monkey"),
            .init(char: "🐔", keywords: "chicken"),
            .init(char: "🐧", keywords: "penguin"),
            .init(char: "🐦", keywords: "bird"),
            .init(char: "🐤", keywords: "chick"),
            .init(char: "🦆", keywords: "duck"),
            .init(char: "🦉", keywords: "owl"),
            .init(char: "🦅", keywords: "eagle"),
            .init(char: "🦄", keywords: "unicorn"),
            .init(char: "🐝", keywords: "bee"),
            .init(char: "🐛", keywords: "bug caterpillar"),
            .init(char: "🦋", keywords: "butterfly"),
            .init(char: "🐢", keywords: "turtle"),
            .init(char: "🐍", keywords: "snake"),
            .init(char: "🦖", keywords: "trex dinosaur"),
            .init(char: "🐳", keywords: "whale"),
            .init(char: "🐬", keywords: "dolphin"),
            .init(char: "🐟", keywords: "fish"),
            .init(char: "🦈", keywords: "shark"),
            .init(char: "🐙", keywords: "octopus"),
            .init(char: "🦑", keywords: "squid"),
            .init(char: "🦞", keywords: "lobster"),
            .init(char: "🦀", keywords: "crab"),
            .init(char: "🐊", keywords: "crocodile"),
            .init(char: "🐅", keywords: "tiger"),
            .init(char: "🐆", keywords: "leopard"),
            .init(char: "🦓", keywords: "zebra"),
            .init(char: "🦒", keywords: "giraffe"),
            .init(char: "🐘", keywords: "elephant"),
            .init(char: "🦏", keywords: "rhino"),
            .init(char: "🦛", keywords: "hippo"),
            .init(char: "🐎", keywords: "horse"),
            .init(char: "🐑", keywords: "sheep"),
            .init(char: "🌵", keywords: "cactus"),
            .init(char: "🌲", keywords: "tree evergreen"),
            .init(char: "🌳", keywords: "tree deciduous"),
            .init(char: "🌴", keywords: "palm tree"),
            .init(char: "🌱", keywords: "seedling"),
            .init(char: "🌿", keywords: "herb leaf"),
            .init(char: "🍀", keywords: "clover luck"),
            .init(char: "🍁", keywords: "maple leaf"),
            .init(char: "🌷", keywords: "tulip"),
            .init(char: "🌹", keywords: "rose"),
            .init(char: "🌺", keywords: "hibiscus flower"),
            .init(char: "🌻", keywords: "sunflower"),
            .init(char: "🌼", keywords: "blossom"),
            .init(char: "🌸", keywords: "cherry blossom"),
            .init(char: "💐", keywords: "bouquet flowers"),
            .init(char: "🍄", keywords: "mushroom"),
        ]),
        EmojiCategory(name: "Food & Drink", emojis: [
            .init(char: "🍎", keywords: "apple red"),
            .init(char: "🍐", keywords: "pear"),
            .init(char: "🍊", keywords: "orange tangerine"),
            .init(char: "🍋", keywords: "lemon"),
            .init(char: "🍌", keywords: "banana"),
            .init(char: "🍉", keywords: "watermelon"),
            .init(char: "🍇", keywords: "grapes"),
            .init(char: "🍓", keywords: "strawberry"),
            .init(char: "🫐", keywords: "blueberries"),
            .init(char: "🍈", keywords: "melon"),
            .init(char: "🍒", keywords: "cherry"),
            .init(char: "🍑", keywords: "peach"),
            .init(char: "🥭", keywords: "mango"),
            .init(char: "🍍", keywords: "pineapple"),
            .init(char: "🥥", keywords: "coconut"),
            .init(char: "🥝", keywords: "kiwi"),
            .init(char: "🍅", keywords: "tomato"),
            .init(char: "🥑", keywords: "avocado"),
            .init(char: "🌽", keywords: "corn"),
            .init(char: "🌶️", keywords: "pepper hot"),
            .init(char: "🥕", keywords: "carrot"),
            .init(char: "🥔", keywords: "potato"),
            .init(char: "🍞", keywords: "bread"),
            .init(char: "🥐", keywords: "croissant"),
            .init(char: "🥯", keywords: "bagel"),
            .init(char: "🧀", keywords: "cheese"),
            .init(char: "🥚", keywords: "egg"),
            .init(char: "🍳", keywords: "egg cooking"),
            .init(char: "🥞", keywords: "pancakes"),
            .init(char: "🥓", keywords: "bacon"),
            .init(char: "🥩", keywords: "steak meat"),
            .init(char: "🍗", keywords: "chicken leg"),
            .init(char: "🌭", keywords: "hot dog"),
            .init(char: "🍔", keywords: "burger hamburger"),
            .init(char: "🍟", keywords: "fries"),
            .init(char: "🍕", keywords: "pizza"),
            .init(char: "🥪", keywords: "sandwich"),
            .init(char: "🌮", keywords: "taco"),
            .init(char: "🌯", keywords: "burrito"),
            .init(char: "🥗", keywords: "salad"),
            .init(char: "🍝", keywords: "spaghetti pasta"),
            .init(char: "🍣", keywords: "sushi"),
            .init(char: "🍱", keywords: "bento"),
            .init(char: "🍦", keywords: "ice cream"),
            .init(char: "🍰", keywords: "cake"),
            .init(char: "🎂", keywords: "birthday cake"),
            .init(char: "🍪", keywords: "cookie"),
            .init(char: "🍫", keywords: "chocolate"),
            .init(char: "🍩", keywords: "donut"),
            .init(char: "🍿", keywords: "popcorn"),
            .init(char: "☕", keywords: "coffee"),
            .init(char: "🍵", keywords: "tea"),
            .init(char: "🧋", keywords: "boba bubble tea"),
            .init(char: "🍺", keywords: "beer"),
            .init(char: "🍷", keywords: "wine"),
            .init(char: "🥂", keywords: "champagne cheers"),
            .init(char: "🍸", keywords: "cocktail"),
            .init(char: "🥤", keywords: "soda drink"),
        ]),
        EmojiCategory(name: "Activities", emojis: [
            .init(char: "⚽", keywords: "soccer football"),
            .init(char: "🏀", keywords: "basketball"),
            .init(char: "🏈", keywords: "football american"),
            .init(char: "⚾", keywords: "baseball"),
            .init(char: "🎾", keywords: "tennis"),
            .init(char: "🏐", keywords: "volleyball"),
            .init(char: "🏉", keywords: "rugby"),
            .init(char: "🎱", keywords: "pool billiards"),
            .init(char: "🏓", keywords: "ping pong"),
            .init(char: "🏸", keywords: "badminton"),
            .init(char: "🥊", keywords: "boxing"),
            .init(char: "🥋", keywords: "martial arts"),
            .init(char: "⛳", keywords: "golf"),
            .init(char: "🎣", keywords: "fishing"),
            .init(char: "🤿", keywords: "diving"),
            .init(char: "🎽", keywords: "running shirt"),
            .init(char: "🛹", keywords: "skateboard"),
            .init(char: "🎿", keywords: "ski"),
            .init(char: "🏂", keywords: "snowboard"),
            .init(char: "🏋️", keywords: "weightlifting gym"),
            .init(char: "🤺", keywords: "fencing"),
            .init(char: "🤼", keywords: "wrestling"),
            .init(char: "🤸", keywords: "cartwheel"),
            .init(char: "⛹️", keywords: "bouncing ball"),
            .init(char: "🚴", keywords: "biking cycling"),
            .init(char: "🧘", keywords: "yoga meditation"),
            .init(char: "🎯", keywords: "target dart"),
            .init(char: "🎮", keywords: "video game gaming"),
            .init(char: "🕹️", keywords: "joystick gaming"),
            .init(char: "🎲", keywords: "dice"),
            .init(char: "🧩", keywords: "puzzle"),
            .init(char: "🎨", keywords: "art palette"),
            .init(char: "🎭", keywords: "theater drama"),
            .init(char: "🎬", keywords: "movie clapper"),
            .init(char: "🎤", keywords: "microphone karaoke"),
            .init(char: "🎧", keywords: "headphones"),
            .init(char: "🎼", keywords: "music score"),
            .init(char: "🎹", keywords: "piano"),
            .init(char: "🥁", keywords: "drum"),
            .init(char: "🎸", keywords: "guitar"),
            .init(char: "🎺", keywords: "trumpet"),
            .init(char: "🎻", keywords: "violin"),
        ]),
        EmojiCategory(name: "Travel & Places", emojis: [
            .init(char: "🚗", keywords: "car automobile"),
            .init(char: "🚕", keywords: "taxi"),
            .init(char: "🚙", keywords: "suv"),
            .init(char: "🚌", keywords: "bus"),
            .init(char: "🚎", keywords: "trolley"),
            .init(char: "🏎️", keywords: "race car"),
            .init(char: "🚓", keywords: "police car"),
            .init(char: "🚑", keywords: "ambulance"),
            .init(char: "🚒", keywords: "fire truck"),
            .init(char: "🚐", keywords: "minibus van"),
            .init(char: "🚚", keywords: "truck"),
            .init(char: "🚛", keywords: "lorry"),
            .init(char: "🛻", keywords: "pickup truck"),
            .init(char: "🚜", keywords: "tractor"),
            .init(char: "🏍️", keywords: "motorcycle"),
            .init(char: "🛵", keywords: "scooter"),
            .init(char: "🚲", keywords: "bicycle bike"),
            .init(char: "🛴", keywords: "kick scooter"),
            .init(char: "🚂", keywords: "locomotive train"),
            .init(char: "🚆", keywords: "train"),
            .init(char: "🚇", keywords: "metro subway"),
            .init(char: "🚊", keywords: "tram"),
            .init(char: "🚝", keywords: "monorail"),
            .init(char: "✈️", keywords: "airplane flight"),
            .init(char: "🛫", keywords: "takeoff"),
            .init(char: "🛬", keywords: "landing"),
            .init(char: "🚀", keywords: "rocket"),
            .init(char: "🛸", keywords: "ufo"),
            .init(char: "🚁", keywords: "helicopter"),
            .init(char: "⛵", keywords: "sailboat"),
            .init(char: "🚤", keywords: "speedboat"),
            .init(char: "🛥️", keywords: "motor boat"),
            .init(char: "🚢", keywords: "ship"),
            .init(char: "⚓", keywords: "anchor"),
            .init(char: "🏠", keywords: "house home"),
            .init(char: "🏡", keywords: "home garden"),
            .init(char: "🏢", keywords: "office building"),
            .init(char: "🏦", keywords: "bank"),
            .init(char: "🏨", keywords: "hotel"),
            .init(char: "🏫", keywords: "school"),
            .init(char: "🏥", keywords: "hospital"),
            .init(char: "🏪", keywords: "convenience store"),
            .init(char: "🏬", keywords: "department store"),
            .init(char: "🏭", keywords: "factory"),
            .init(char: "🗼", keywords: "tokyo tower"),
            .init(char: "🗽", keywords: "statue liberty"),
            .init(char: "🗿", keywords: "moai"),
            .init(char: "🏔️", keywords: "mountain snow"),
            .init(char: "🏖️", keywords: "beach"),
            .init(char: "🏝️", keywords: "island"),
            .init(char: "🌋", keywords: "volcano"),
            .init(char: "🗺️", keywords: "world map"),
            .init(char: "🌍", keywords: "earth globe"),
        ]),
        EmojiCategory(name: "Objects", emojis: [
            .init(char: "💻", keywords: "laptop computer"),
            .init(char: "🖥️", keywords: "desktop computer"),
            .init(char: "⌨️", keywords: "keyboard"),
            .init(char: "🖱️", keywords: "mouse computer"),
            .init(char: "🖨️", keywords: "printer"),
            .init(char: "📱", keywords: "phone mobile"),
            .init(char: "📲", keywords: "phone arrow"),
            .init(char: "☎️", keywords: "telephone"),
            .init(char: "📞", keywords: "phone receiver"),
            .init(char: "📷", keywords: "camera"),
            .init(char: "📸", keywords: "camera flash"),
            .init(char: "📹", keywords: "video camera"),
            .init(char: "🎥", keywords: "movie camera"),
            .init(char: "📺", keywords: "tv television"),
            .init(char: "📻", keywords: "radio"),
            .init(char: "🎙️", keywords: "studio mic"),
            .init(char: "💡", keywords: "lightbulb idea"),
            .init(char: "🔦", keywords: "flashlight"),
            .init(char: "🕯️", keywords: "candle"),
            .init(char: "🔋", keywords: "battery"),
            .init(char: "🔌", keywords: "plug electric"),
            .init(char: "💾", keywords: "floppy disk save"),
            .init(char: "💿", keywords: "cd disk"),
            .init(char: "📀", keywords: "dvd"),
            .init(char: "📚", keywords: "books library"),
            .init(char: "📖", keywords: "book open"),
            .init(char: "📰", keywords: "newspaper"),
            .init(char: "📝", keywords: "memo note"),
            .init(char: "✏️", keywords: "pencil"),
            .init(char: "🖊️", keywords: "pen"),
            .init(char: "🖌️", keywords: "paintbrush"),
            .init(char: "🖍️", keywords: "crayon"),
            .init(char: "📌", keywords: "pin pushpin"),
            .init(char: "📎", keywords: "paperclip"),
            .init(char: "🔑", keywords: "key"),
            .init(char: "🔒", keywords: "lock"),
            .init(char: "🔓", keywords: "unlock"),
            .init(char: "🛡️", keywords: "shield"),
            .init(char: "🔧", keywords: "wrench tool"),
            .init(char: "🔨", keywords: "hammer"),
            .init(char: "⚙️", keywords: "gear settings"),
            .init(char: "💰", keywords: "money bag"),
            .init(char: "💵", keywords: "dollar cash"),
            .init(char: "💳", keywords: "credit card"),
            .init(char: "🧾", keywords: "receipt invoice"),
            .init(char: "📊", keywords: "bar chart"),
            .init(char: "📈", keywords: "chart up"),
            .init(char: "📉", keywords: "chart down"),
            .init(char: "🎁", keywords: "gift present"),
            .init(char: "🎈", keywords: "balloon"),
            .init(char: "🎉", keywords: "party popper"),
            .init(char: "🎊", keywords: "confetti"),
            .init(char: "✉️", keywords: "envelope email"),
            .init(char: "📧", keywords: "email"),
            .init(char: "📦", keywords: "package box"),
            .init(char: "📫", keywords: "mailbox"),
        ]),
        EmojiCategory(name: "Symbols", emojis: [
            .init(char: "❤️", keywords: "heart red love"),
            .init(char: "🧡", keywords: "orange heart"),
            .init(char: "💛", keywords: "yellow heart"),
            .init(char: "💚", keywords: "green heart"),
            .init(char: "💙", keywords: "blue heart"),
            .init(char: "💜", keywords: "purple heart"),
            .init(char: "🖤", keywords: "black heart"),
            .init(char: "🤍", keywords: "white heart"),
            .init(char: "🤎", keywords: "brown heart"),
            .init(char: "💔", keywords: "broken heart"),
            .init(char: "💖", keywords: "sparkling heart"),
            .init(char: "💗", keywords: "growing heart"),
            .init(char: "💕", keywords: "two hearts"),
            .init(char: "💞", keywords: "revolving hearts"),
            .init(char: "💓", keywords: "beating heart"),
            .init(char: "⭐", keywords: "star"),
            .init(char: "🌟", keywords: "glowing star"),
            .init(char: "✨", keywords: "sparkles"),
            .init(char: "⚡", keywords: "lightning bolt"),
            .init(char: "🔥", keywords: "fire flame"),
            .init(char: "💯", keywords: "hundred 100"),
            .init(char: "💢", keywords: "anger"),
            .init(char: "💥", keywords: "boom collision"),
            .init(char: "💦", keywords: "sweat drops"),
            .init(char: "💨", keywords: "dash wind"),
            .init(char: "✅", keywords: "check mark"),
            .init(char: "❌", keywords: "cross mark x"),
            .init(char: "❓", keywords: "question mark"),
            .init(char: "❗", keywords: "exclamation"),
            .init(char: "⚠️", keywords: "warning"),
            .init(char: "🚫", keywords: "no entry prohibited"),
            .init(char: "♻️", keywords: "recycle"),
            .init(char: "🔔", keywords: "bell notification"),
            .init(char: "🔕", keywords: "no bell mute"),
            .init(char: "🎵", keywords: "music note"),
            .init(char: "🎶", keywords: "music notes"),
            .init(char: "🌈", keywords: "rainbow"),
            .init(char: "☀️", keywords: "sun sunny"),
            .init(char: "🌤️", keywords: "sun cloud"),
            .init(char: "⛅", keywords: "cloud sun"),
            .init(char: "☁️", keywords: "cloud"),
            .init(char: "🌧️", keywords: "rain"),
            .init(char: "⛈️", keywords: "thunderstorm"),
            .init(char: "❄️", keywords: "snowflake snow"),
            .init(char: "☃️", keywords: "snowman"),
            .init(char: "🌙", keywords: "moon crescent"),
        ]),
    ]

    static func filtered(_ query: String) -> [EmojiCategory] {
        let q = query.trimmingCharacters(in: .whitespaces).lowercased()
        guard !q.isEmpty else { return categories }
        return categories.compactMap { cat in
            let matches = cat.emojis.filter { $0.keywords.localizedCaseInsensitiveContains(q) }
            return matches.isEmpty ? nil : EmojiCategory(name: cat.name, emojis: matches)
        }
    }
}
